squid:
<<<<<<< HEAD
  restart: always
=======
>>>>>>> branch 'master' of git@github.com:nouchka/docker-proxy.git
  image: "nouchka/squid"
  container_name: "proxy"
  ports:
    - 3128:3128
  links:
    - privoxy
privoxy:
  image: "nouchka/privoxy"
  volumes:
    - ./privoxy/custom:/etc/privoxy/custom
